### ISSUE TITLE
Core: Semantics equivalent to Unity's API

### ISSUE THREAD

**Issue by martin-azpillaga** [martin-azpillaga/M#33]
The Unity game engine provides a good base of built in components for frequently used game interactions.

Providing access to an equivalent set of components is desirable.

- Animation

- [ ] Sprite sheet animation

- [ ] 2d rigging

- [ ] 3d rigging

- [ ] Non visual animation curves

- Audio

- [x] Play on awake

- [ ] Audio mixing

- [ ] placeholder looping music

- Artificial intelligence

- [ ] Reinforcement learning

- [ ] Curriculum learning

- [ ] Curiosity learning

- [ ] Navigation

- Input

- [ ] Keyboard

- [ ] Mouse

- [x] Gamepad

- [ ] Touch controls

- Networking

- Rendering

- [x] placeholder images

- [ ] placeholder sprites

- [ ] placeholder meshes

- [ ] placeholder materials

- Time

- [x] Timer events

- [ ] Cut scenes

- [ ] Timeline support

- Physics

- [ ] convex colliders

- [ ] concave / mesh collider's

- [x] collision events

- [ ] 2d and 3d physics

- User Interface

- [x] text image and button widgets

- [ ] sliders scrolls and advanced widgets

- [ ] ui events

- Mixed reality

- [ ] VR support

- [ ] AR support
